print("Band Name Generator!")
print('---------------------')
person_name = input("What's your name ? ")
pet_name = input("What's your pet name ? ")
print('----------------------------------')
print("Your band name can be " + person_name + "-" + pet_name)